version: '3.8'

services:
  spring-app:
    build: .
    image: snowyxd/devops_gamix
    container_name: spring-app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/springdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: springdb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
    driver: local
