version: "3.8"

services:
  mysqldb:
    image: mysql:8.2.0
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=devops
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
  app-timesheet:
    depends_on:
      - mysqldb
    image: moenesgueni559/gestion-station-ski-1.0
    restart: on-failure
    ports:
      - 8089:8089
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url=jdbc:mysql://localhost:3306/stationSki?createDatabaseIfNotExist=true",
        "spring.datasource.username=root",
        "spring.datasource.password=",
        "spring.jpa.show-sql=true",
        "spring.jpa.hibernate.ddl-auto=update",
        "spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect",
    }'
    stdin_open: true
    tty: true

volumes:
  db: