---
# PersistentVolumeClaim for MySQL data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
# MySQL Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "0000"
            - name: MYSQL_DATABASE
              value: "stationSki"
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-storage
          livenessProbe:
            exec:
              command:
                - "mysqladmin"
                - "ping"
                - "-h"
                - "localhost"
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - "mysqladmin"
                - "ping"
                - "-h"
                - "localhost"
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc

---
# MySQL Service
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql
  clusterIP: None  # Headless service for internal access

---
# App Deployment Spring
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gestion-station-ski-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gestion-station-ski-app
  template:
    metadata:
      labels:
        app: gestion-station-ski-app
    spec:
      containers:
        - name: app
          image: mohamedrayen/sky_devops:2
          env:
            - name: SERVER_SERVLET_CONTEXT_PATH
              value: "/api"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql:3306/stationSki?createDatabaseIfNotExist=true"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "0000"
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
              value: "org.hibernate.dialect.MySQL8Dialect"
            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              value: "prometheus"
            - name: MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED
              value: "true"
            - name: MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED
              value: "true"
          ports:
            - containerPort: 8082
          readinessProbe:
            httpGet:
              path: /api/piste/all
              port: 8082
            initialDelaySeconds: 5
            periodSeconds: 10

---
# App Service
apiVersion: v1
kind: Service
metadata:
  name: gestion-station-ski-service
spec:
  ports:
    - port: 8082
      targetPort: 8082
  selector:
    app: gestion-station-ski-app
  type: ClusterIP

---
# Frontend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sky-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sky-frontend
  template:
    metadata:
      labels:
        app: sky-frontend
    spec:
      containers:
        - name: frontend
          image: mohamedrayen/sky-front:3
          ports:
            - containerPort: 3001
          readinessProbe:
            httpGet:
              path: /
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 10

---
# Frontend Service
apiVersion: v1
kind: Service
metadata:
  name: sky-frontend-service
spec:
  ports:
    - port: 3001
      targetPort: 3001
  selector:
    app: sky-frontend
  type: ClusterIP
